//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA47_Team9B_UIDesignTemplate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.TransactionIDs = new HashSet<TransactionID>();
        }
    
        public string StaffID { get; set; }
        public string StaffName { get; set; }
        public string StaffPosition { get; set; }
        public string StaffEmail { get; set; }
        public Nullable<double> StaffContactNo_ { get; set; }
        public string StaffAddress { get; set; }
        public string City { get; set; }
        public Nullable<double> Postalcode { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionID> TransactionIDs { get; set; }
    }
}
