//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA47_Team9B_UIDesignTemplate
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionID
    {
        public string TransactionID1 { get; set; }
        public string MemberID { get; set; }
        public short BookID { get; set; }
        public Nullable<System.DateTime> DateIssue { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public Nullable<System.DateTime> DateActualReturn { get; set; }
        public string LoanStatus { get; set; }
        public string Remarks { get; set; }
        public string StaffID { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Member Member { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
